use food_app_project;

--phase-1 Exploratory analysis
--total revenue generated by the food delivery app

select sum(order_amount-discount) as total_revenue
from orders;

---- 2. TOTAL ORDER PER CITY

SELECT r.city,
       COUNT(*) AS total_orders
FROM orders o
JOIN restaurants r
    ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY total_orders DESC;

--3 -- Top 10 Customers by Spending...

SELECT
    c.customer_id,
    c.name,
    c.city,
    SUM(o.order_amount) AS total_spent
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.name,
    c.city
ORDER BY total_spent DESC
LIMIT 10;

--Phase 2 cutomer segmentation.

--4. Customer Category (Gold / Silver / Bronze)

SELECT
    c.customer_id,
    c.name,
    SUM(o.order_amount) AS total_spent,
    CASE
        WHEN SUM(o.order_amount) >= 5000 THEN 'Gold'
        WHEN SUM(o.order_amount) >= 2000 THEN 'Silver'
        ELSE 'Bronze'
    END AS customer_category
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
ORDER BY total_spent DESC;

--Like we have different/altrernative method like based on orders..

SELECT
    c.customer_id,
    c.name,
    COUNT(o.order_id) AS total_orders,
    CASE
        WHEN COUNT(o.order_id) >= 8 THEN 'Gold'
        WHEN COUNT(o.order_id) >= 5 THEN 'Silver'
        ELSE 'Bronze'
    END AS customer_category
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
ORDER BY total_orders DESC;
;
-- But i think the best part is categorized by spent..

--5 Top 10 Restaurants by Revenue

SELECT
    r.restaurant_id,
    r.restaurant_name,
    r.city,
    SUM(o.order_amount-o.discount) AS total_revenue
FROM orders o
JOIN restaurants r
    ON  o.restaurant_id = r.restaurant_id 
GROUP BY
    r.restaurant_id,
    r.restaurant_name,
    r.city
ORDER BY total_revenue DESC
LIMIT 10;


--6.avg rating vs reveneu for resturant..

-- Average Rating vs Revenue for Restaurants

SELECT
    r.restaurant_id,
    r.restaurant_name,
    r.rating AS avg_rating,
    SUM(o.order_amount - o.discount) AS total_revenue
FROM restaurants r
JOIN orders o
    ON r.restaurant_id = o.restaurant_id
GROUP BY
    r.restaurant_id,
    r.restaurant_name,
    r.rating
ORDER BY total_revenue DESC;

--Phase 4 delivery performance
--7.Avg delivery time for city

-- Average Delivery Time by City

SELECT r.city,
       AVG(o.delivery_time) AS avg_delivery_time
FROM orders o
JOIN restaurants r
    ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY avg_delivery_time;

--8 Late Deliveries (Above 45 Minutes)

SELECT
    order_id,
    customer_id,
    restaurant_id,
    delivery_time
FROM orders
WHERE delivery_time > 45
ORDER BY delivery_time DESC;

--PHASE 5 — PAYMENT & DISCOUNT ANALYSIS
--9.Payment Method Distribution

SELECT
    payment_method,
    COUNT(*) AS count
FROM orders
GROUP BY payment_method
ORDER BY count DESC;


--10. Discount Impact on Revenue


SELECT
    CASE
        WHEN discount > 0 THEN 'With Discount'
        ELSE 'Without Discount'
    END AS discount_category,

    COUNT(*) AS total_orders,
    SUM(order_amount) AS gross_revenue,
    SUM(discount) AS total_discount,
    SUM(order_amount - discount) AS net_revenue

FROM orders
GROUP BY discount_category;


--Phase 6 (ADVANCE SQL)

-- 11 monthly revenue using cte
WITH monthly_revenue AS (
    SELECT 
        month(order_date) as month,
        SUM(order_amount - discount) AS revenue
    FROM orders
    GROUP BY month
)
SELECT month, revenue
FROM monthly_revenue
ORDER BY month;

--12 Rank Restaurants by Revenue

SELECT
    r.restaurant_id,
    r.restaurant_name,
    SUM(o.order_amount) AS total_revenue,
    RANK() OVER (
        ORDER BY SUM(o.order_amount) DESC
    ) AS revenue_rank
FROM restaurants r
JOIN orders o
    ON r.restaurant_id = o.restaurant_id
GROUP BY
    r.restaurant_id,
    r.restaurant_name;

--13 Above Average Revenue Restaurants

SELECT
    restaurant_name,
    total_revenue
FROM
(
    SELECT
        r.restaurant_name,
        SUM(o.order_amount) AS total_revenue
    FROM restaurants r
    JOIN orders o
        ON r.restaurant_id = o.restaurant_id
    GROUP BY r.restaurant_name
) AS restaurant_revenue
WHERE total_revenue >
(
    SELECT AVG(total_revenue)
    FROM
    (
        SELECT
            SUM(order_amount) AS total_revenue
        FROM orders
        GROUP BY restaurant_id
    ) AS avg_revenue
)
ORDER BY total_revenue DESC;

---- 14 create revenue view
CREATE VIEW revenue_view AS
SELECT 
    r.restaurant_id,
    r.restaurant_name,
    r.city,
    SUM(o.order_amount - o.discount) AS total_revenue
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name, r.city;

-- 15 stored procedure get top n restaurants

CREATE PROCEDURE get_top_n_restaurants(IN n INT)
BEGIN
    SET @limit_val = n;

    SET @sql_query = CONCAT(
        'SELECT 
            restaurant_id,
            restaurant_name,
            city,
            total_revenue
        FROM revenue_view
        ORDER BY total_revenue DESC
        LIMIT ', @limit_val
    );

    PREPARE stmt FROM @sql_query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END

call get_top_n_restaurants(5);

-- PHASE-B

-- INDEX ON ORDER_DATE
CREATE INDEX idx_order_date ON orders(order_date);


-- index on customer name  COMMENT
CREATE INDEX i_customer_name ON customers(name);

-- Index on restaurant_name

CREATE INDEX i_restaurant_name ON restaurants(restaurant_name);


PHASE 9 —Automation Logic

--16. Auto logic for High Value Order
create table high_value_orders_log (
    log_id int primary key auto_increment,
    order_id int,
    customer_id int,
    restaurant_id int,
    order_amount decimal(10,2),
    log_date datetime default current_timestamp
);

CREATE TRIGGER trg_high_value_order
AFTER INSERT ON orders
FOR EACH ROW
BEGIN
    IF NEW.order_amount > 1000 THEN
        INSERT INTO high_value_orders_log
        (order_id, customer_id, restaurant_id, order_amount)
        VALUES
        (NEW.order_id, NEW.customer_id, NEW.restaurant_id, NEW.order_amount);
    END IF;
END;

insert into orders values (1010, 231, 138, '2024-01-01', 1200.00, 100.00, 'Credit Card', 30);
insert into orders values (1011, 232, 139, '2024-01-02', 8000.00, 50.00, 'Cash', 25);



--17. cretae trigger to prevent negative discount
CREATE TRIGGER trg_prevent_negative_discount
BEFORE INSERT ON orders
FOR EACH ROW
BEGIN
    IF NEW.discount < 0 THEN
        SET NEW.discount = 0;
    END IF;
END;

insert into orders values (1014, 231, 138, '2024-01-03', 500.00, -20.00, 'UPI', 20);


select * from orders where order_id = 1014; 


--18 delivery delay warning
create table delivery_delay_log (
    log_id int primary key auto_increment,
    order_id int,
    customer_id int,
    restaurant_id int,
    delivery_time int,
    created_at timestamp default current_timestamp
);

create trigger log_late_delivery
AFTER insert ON orders
for each row
BEGIN
    IF NEW.delivery_time > 45 THEN
        INSERT INTO delivery_delay_log (order_id, customer_id, restaurant_id, delivery_time)
        VALUES (NEW.order_id, NEW.customer_id, NEW.restaurant_id, NEW.delivery_time);
    END IF;
END;

insert into orders values (1020, 231, 138, '2024-01-01', 1200.00, 100.00, 'Credit Card', 30);
insert into orders values (1021, 232, 139, '2024-01-02', 8000.00, 50.00, 'Cash', 25);



